const CUSTOMERS_SERVICE_API_KEY = process.env.CUSTOMERS_SERVICE_API_KEY;
const CUSTOMERS_SERVICE_URL = process.env.CUSTOMERS_SERVICE_URL;


export const CUSTOMER_SERVICE = {
    url: CUSTOMERS_SERVICE_URL,
    api_key: CUSTOMERS_SERVICE_API_KEY
};